### ISSUE TITLE
SourceGuardian http no longer redirects

### ISSUE THREAD

**Issue by erikgeurts** [adserverplugins/apLoader#1]
The apLoader configuration step to download the SourceGuardian extension links to a URL http://www.sourceguardian.com/loaders/download.php that used to redirect to https://www.sourceguardian.com/loaders/download.php . For some reason, it's no longer redirecting. We should update the apLoader plugin to automatically link to the secure address.

**Comment by mbeccati** [comment]
Works for me...

**Comment by erikgeurts** [comment]
if I click the button from within the apLoader, I end up on the http URL and it doesn't redirect.

**Comment by erikgeurts** [comment]
It may be because it's actually landing on a form that's not being submitted because it's not a secure address:
![image](https://github.com/adserverplugins/apLoader/assets/5102461/2001d1b0-1d01-4e68-8f4d-b1deb2d2c679)

**Comment by mbeccati** [comment]
Ok, now I get it

**Comment by erikgeurts** [comment]
This was caused by a misunderstanding. This was actually fixed already in v1.4.0 in 2021, but the page at https://www.adserverplugins.com/adserverplugins-com-loader/ accidentally still offered to download the v1.3.1 version of the apLoader plugin/. This is now up to date.
